### ISSUE TITLE
Array handling bug (NullPointerException)

### ISSUE THREAD

**Issue by uscexp** [uscexp/SplShell#3]
Fix it

com.github.uscexp.splshell.exception.SplShellException: SplShell interpretation error!
	at com.github.uscexp.splshell.interpreter.SplInterpreter.executeFromStringInput(SplInterpreter.java:142)
	at com.github.uscexp.splshell.interpreter.SplInterpreter.executeFromFile(SplInterpreter.java:92)
	at com.github.uscexp.splshell.interpreter.SplInterpreter.executeFromFile(SplInterpreter.java:74)
	at com.github.uscexp.splshell.interpreter.SplInterpreterTest.testExecuteFromStringInputFromFileStringCharset(SplInterpreterTest.java:687)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: com.github.uscexp.grappa.extension.exception.AstInterpreterException: Can't build/interpret AstTreeNodes for parser class com.github.uscexp.splshell.parser.SplParser
	at com.github.uscexp.grappa.extension.interpreter.AstInterpreter.interpret(AstInterpreter.java:75)
	at com.github.uscexp.grappa.extension.interpreter.AstInterpreter.interpretForewardOrder(AstInterpreter.java:54)
	at com.github.uscexp.splshell.interpreter.SplInterpreter.executeFromStringInput(SplInterpreter.java:140)
	... 26 more
Caused by: com.github.uscexp.grappa.extension.exception.AstInterpreterException: Can't build/interpret AstTreeNodes for parser class com.github.uscexp.splshell.parser.SplParser
	at com.github.uscexp.grappa.extension.interpreter.AstInterpreter.interpret(AstInterpreter.java:75)
	at com.github.uscexp.grappa.extension.interpreter.AstInterpreter.interpretForewardOrder(AstInterpreter.java:54)
	at com.github.uscexp.splshell.interpreter.ScriptMethodDefinition.invoke(ScriptMethodDefinition.java:73)
	at com.github.uscexp.splshell.parser.AstMethodCallStatementTreeNode.interpretAfterChilds(AstMethodCallStatementTreeNode.java:83)
	at com.github.uscexp.grappa.extension.nodes.AstTreeNode.interpretIt(AstTreeNode.java:53)
	at com.github.uscexp.grappa.extension.nodes.AstTreeNode.interpretIt(AstTreeNode.java:44)
	at com.github.uscexp.grappa.extension.nodes.AstTreeNode.interpretIt(AstTreeNode.java:44)
	at com.github.uscexp.splshell.parser.AstWhileStatementTreeNode.interpretAfterChilds(AstWhileStatementTreeNode.java:43)
	at com.github.uscexp.grappa.extension.nodes.AstTreeNode.interpretIt(AstTreeNode.java:53)
	at com.github.uscexp.grappa.extension.nodes.AstTreeNode.interpretIt(AstTreeNode.java:44)
	at com.github.uscexp.grappa.extension.nodes.AstTreeNode.interpretIt(AstTreeNode.java:44)
	at com.github.uscexp.splshell.parser.AstWhileStatementTreeNode.interpretAfterChilds(AstWhileStatementTreeNode.java:43)
	at com.github.uscexp.grappa.extension.nodes.AstTreeNode.interpretIt(AstTreeNode.java:53)
	at com.github.uscexp.grappa.extension.nodes.AstTreeNode.interpretIt(AstTreeNode.java:44)
	at com.github.uscexp.grappa.extension.nodes.AstTreeNode.interpretIt(AstTreeNode.java:44)
	at com.github.uscexp.splshell.parser.AstWhileStatementTreeNode.interpretAfterChilds(AstWhileStatementTreeNode.java:43)
	at com.github.uscexp.grappa.extension.nodes.AstTreeNode.interpretIt(AstTreeNode.java:53)
	at com.github.uscexp.grappa.extension.nodes.AstTreeNode.interpretIt(AstTreeNode.java:44)
	at com.github.uscexp.grappa.extension.nodes.AstTreeNode.interpretIt(AstTreeNode.java:44)
	at com.github.uscexp.grappa.extension.nodes.AstTreeNode.interpretIt(AstTreeNode.java:44)
	at com.github.uscexp.grappa.extension.nodes.AstTreeNode.interpretIt(AstTreeNode.java:44)
	at com.github.uscexp.grappa.extension.interpreter.AstInterpreter.interpret(AstInterpreter.java:73)
	... 28 more
Caused by: java.lang.NullPointerException
	at com.github.uscexp.grappa.extension.interpreter.type.Primitive.<init>(Primitive.java:176)
	at com.github.uscexp.splshell.parser.AstBaseCommandTreeNode.getPrimitive(AstBaseCommandTreeNode.java:101)
	at com.github.uscexp.splshell.parser.AstCalculationExpressionTreeNode.process(AstCalculationExpressionTreeNode.java:25)
	at com.github.uscexp.splshell.parser.AstAdditiveExpressionTreeNode.interpretAfterChilds(AstAdditiveExpressionTreeNode.java:24)
	at com.github.uscexp.grappa.extension.nodes.AstTreeNode.interpretIt(AstTreeNode.java:53)
	at com.github.uscexp.grappa.extension.nodes.AstTreeNode.interpretIt(AstTreeNode.java:44)
	at com.github.uscexp.grappa.extension.nodes.AstTreeNode.interpretIt(AstTreeNode.java:44)
	at com.github.uscexp.grappa.extension.nodes.AstTreeNode.interpretIt(AstTreeNode.java:44)
	at com.github.uscexp.grappa.extension.nodes.AstTreeNode.interpretIt(AstTreeNode.java:44)
	at com.github.uscexp.grappa.extension.nodes.AstTreeNode.interpretIt(AstTreeNode.java:44)
	at com.github.uscexp.grappa.extension.nodes.AstTreeNode.interpretIt(AstTreeNode.java:44)
	at com.github.uscexp.grappa.extension.nodes.AstTreeNode.interpretIt(AstTreeNode.java:44)
	at com.github.uscexp.grappa.extension.nodes.AstTreeNode.interpretIt(AstTreeNode.java:44)
	at com.github.uscexp.grappa.extension.nodes.AstTreeNode.interpretIt(AstTreeNode.java:44)
	at com.github.uscexp.grappa.extension.nodes.AstTreeNode.interpretIt(AstTreeNode.java:44)
	at com.github.uscexp.grappa.extension.interpreter.AstInterpreter.interpret(AstInterpreter.java:73)
	... 49 more

**Comment by uscexp** [comment]
resolved with pull request https://github.com/uscexp/SplShell/pull/4
